default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password: 
  host: localhost


development:
  <<: *default
  database: mini_shop_development

test:
  <<: *default
  database: mini_shop_test