source 'http://rubygems.org'

gem 'rake'
gem 'sinatra'
gem 'mysql2'
gem 'bcrypt-ruby', '3.1.2', require: 'bcrypt'
gem 'activerecord', '3.2.16', require: 'active_record'
gem 'yajl-ruby', '1.1.0', require: ['yajl', 'yajl/json_gem']
gem 'rack-parser', require: 'rack/parser'
gem 'hashie', '~> 2.1.1'
gem 'sinatra-respond_to'
gem 'sinatra-contrib'
gem 'active_model_serializers', '~> 0.8.1'

group :development do
  gem 'thin'
  gem 'pry'
  gem 'pry-remote'
  gem 'pry-debugger'
  gem 'pry-stack_explorer'
end

group :test do
  gem 'timecop'
  gem 'faker'
  gem 'rspec'
  gem 'shoulda-matchers'
  gem 'factory_girl'
  gem 'database_cleaner'
  gem 'rack-test', require: 'rack/test'
  gem 'simplecov', '~> 0.7.1'
end
