source "http://rubygems.org"

gem "rake"
gem "sinatra"
gem "mysql2"
gem "bcrypt-ruby", "3.1.2"
gem "activerecord", "3.2.15", require: "active_record"
gem "yajl-ruby", "1.1.0", require: "yajl"

group :development do
  gem "thin"
end

group :test do
  gem "rspec"
  gem "factory_girl"
end
