source 'https://rubygems.org'

gem 'rake'
gem 'yajl-ruby', '~> 1.2', require: ['yajl', 'yajl/json_gem']
gem 'hashie', '~> 2.1.1'
gem 'rest-client'
gem 'activesupport', require: ['active_support/inflector', 'active_support/core_ext/object']

group :test do
  gem 'timecop'
  gem 'faker'
  gem 'simplecov', '~> 0.7.1'
  gem 'rspec'
end

group :development, :test do
  gem 'pry'
  gem 'pry-remote'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
end
