source 'https://rubygems.org'

gem 'yajl-ruby', '~> 1.2', require: ['yajl', 'yajl/json_gem']
gem 'hashie', '~> 2.1.1'

group :test do
  gem 'timecop'
  gem 'faker'
  gem 'simplecov', '~> 0.7.1'
  gem 'rspec'
end
